package com.everis.practicacloudcompra.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "inventario2")
public class Producto implements java.io.Serializable {

	private int id;
	private String nombre;
	private int port;
	private int stock;
	@JsonIgnore
	private Set<Compra> compras = new HashSet<Compra>(0);

	public Producto() {
	}

	public Producto(int id, String nombre, int port, int stock) {
		this.id = id;
		this.nombre = nombre;
		this.port = port;
		this.stock = stock;
	}

	public Producto(int id, String nombre, int port, int stock, Set<Compra> compras) {
		this.id = id;
		this.nombre = nombre;
		this.port = port;
		this.stock = stock;
		this.compras = compras;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "port", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	@Column(name = "stock", nullable = false)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Compra> getCompras() {
		return this.compras;
	}

	public void setCompras(Set<Compra> compras) {
		this.compras = compras;
	}

}

