-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 12:52:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventario2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventario2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario2` DEFAULT CHARACTER SET utf8 ;
USE `inventario2` ;

-- -----------------------------------------------------
-- Table `inventario2`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario2`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `port` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario2`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario2`.`compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `fechahora` DATETIME NOT NULL,
  `cantidad` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_compra_producto_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `inventario2`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
